# Generated by Django 5.1.3 on 2024-11-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_creationusermodel_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creationusermodel',
            name='rol',
        ),
        migrations.AlterField(
            model_name='creationusermodel',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='CODIGO'),
        ),
    ]
