# Generated by Django 5.1.3 on 2024-12-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_experienciamodel_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='experienciamodel',
            name='url_company',
            field=models.URLField(default=''),
        ),
    ]
