# Generated by Django 5.1.3 on 2024-12-19 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_experienciamodel_url_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ie', models.CharField(max_length=150)),
                ('carrera', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
