# Generated by Django 5.1.3 on 2024-12-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_capacitymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitymodel',
            name='end_date',
        ),
        migrations.AlterField(
            model_name='capacitymodel',
            name='tiempo',
            field=models.IntegerField(),
        ),
    ]
