# Generated by Django 5.1.3 on 2024-12-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_remove_capacitymodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymodel',
            name='url_company',
            field=models.URLField(default=''),
        ),
    ]
