# Generated by Django 5.1.3 on 2024-12-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_projectmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='urls',
            field=models.CharField(max_length=250, verbose_name=''),
        ),
    ]
