# Generated by Django 5.1.3 on 2025-02-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_projectmodel_urls'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmodel',
            name='url_github',
            field=models.CharField(default='', max_length=250, verbose_name=''),
        ),
    ]
