# Generated by Django 5.1.3 on 2025-02-25 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_projectmodel_url_github'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='capacitymodel',
            name='tiempo',
        ),
        migrations.AddField(
            model_name='capacitymodel',
            name='tiempo_integer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='url_github',
            field=models.CharField(default='', max_length=250, verbose_name='URL GitHub'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='urls',
            field=models.CharField(max_length=250, verbose_name='URL Pagina Web'),
        ),
    ]
